### ISSUE TITLE
Google Fonts over HTTPS

### ISSUE THREAD

**Issue by hetmann** [DevAlien/dripr-ui#12]
You can change the URL stylesheet for Google Fonts from HTTP to HTTPS.

`Mixed Content: The page at 'https://dripr.io/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:400,700'. This request has been blocked; the content must be served over HTTPS.`

**Comment by DevAlien** [comment]
Or I can use `//`so it will use whatever you are using, so when testing in dev it goes to HTTP.
I will change this, thanks :)

**Comment by DevAlien** [comment]
Still have to change this, forgot :(

**Comment by hetmann** [comment]
Don't you worry, when you have time you'll do it :)

**Comment by DevAlien** [comment]
This is now fixed thanks
