### ISSUE TITLE
Mobile friendly version

### ISSUE THREAD

**Issue by ianaz** [DevAlien/dripr-ui#4]
I'd really love to have a mobile friendly version for when people send me pictures on my phone and I have to open them with my mobile browser

**Comment by DevAlien** [comment]
I will work on that, some new design for mobile is definitely needed :)

**Comment by DevAlien** [comment]
This will be implemented with #10

**Comment by DevAlien** [comment]
I've put in production a test branch (newui) it has a mobile friendly version, do you like it?
